package com.netshoes.model.vo;
// Generated 22-Apr-2015 11:39:20 by Hibernate Tools 4.3.1

/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private int bairroCodigo;
     private Cidade cidade;
     private String bairroDescricao;

    public Bairro() {
    }

	
    public Bairro(int bairroCodigo, Cidade cidade) {
        this.bairroCodigo = bairroCodigo;
        this.cidade = cidade;
    }
   
    public int getBairroCodigo() {
        return this.bairroCodigo;
    }
    
    public void setBairroCodigo(int bairroCodigo) {
        this.bairroCodigo = bairroCodigo;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getBairroDescricao() {
        return this.bairroDescricao;
    }
    
    public void setBairroDescricao(String bairroDescricao) {
        this.bairroDescricao = bairroDescricao;
    }
}


