package com.netshoes.model.vo;
// Generated 22-Apr-2015 11:39:20 by Hibernate Tools 4.3.1

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private int cidadeCodigo;
     private Uf uf;
     private String cidadeDescricao;
     private String cidadeCep;

    public Cidade() {
    }

	
    public Cidade(int cidadeCodigo, Uf uf, String cidadeDescricao, String cidadeCep) {
        this.cidadeCodigo = cidadeCodigo;
        this.uf = uf;
        this.cidadeDescricao = cidadeDescricao;
        this.cidadeCep = cidadeCep;
    }
   
    public int getCidadeCodigo() {
        return this.cidadeCodigo;
    }
    
    public void setCidadeCodigo(int cidadeCodigo) {
        this.cidadeCodigo = cidadeCodigo;
    }
    public Uf getUf() {
        return this.uf;
    }
    
    public void setUf(Uf uf) {
        this.uf = uf;
    }
    public String getCidadeDescricao() {
        return this.cidadeDescricao;
    }
    
    public void setCidadeDescricao(String cidadeDescricao) {
        this.cidadeDescricao = cidadeDescricao;
    }
    public String getCidadeCep() {
        return this.cidadeCep;
    }
    
    public void setCidadeCep(String cidadeCep) {
        this.cidadeCep = cidadeCep;
    }
}


