package com.netshoes.model.vo;
// Generated 22-Apr-2015 11:39:20 by Hibernate Tools 4.3.1



/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private int enderecoCodigo;
     private Bairro bairro;
     private String enderecoCep;
     private String enderecoLogradouro;
     private String enderecoComplemento;

    public Endereco() {
    }

	
    public Endereco(int enderecoCodigo, Bairro bairro) {
        this.enderecoCodigo = enderecoCodigo;
        this.bairro = bairro;
    }
    public Endereco(int enderecoCodigo, Bairro bairro, String enderecoCep, String enderecoLogradouro, String enderecoComplemento) {
       this.enderecoCodigo = enderecoCodigo;
       this.bairro = bairro;
       this.enderecoCep = enderecoCep;
       this.enderecoLogradouro = enderecoLogradouro;
       this.enderecoComplemento = enderecoComplemento;
    }
   
    public int getEnderecoCodigo() {
        return this.enderecoCodigo;
    }
    
    public void setEnderecoCodigo(int enderecoCodigo) {
        this.enderecoCodigo = enderecoCodigo;
    }
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }
    public String getEnderecoCep() {
        return this.enderecoCep;
    }
    
    public void setEnderecoCep(String enderecoCep) {
        this.enderecoCep = enderecoCep;
    }
    public String getEnderecoLogradouro() {
        return this.enderecoLogradouro;
    }
    
    public void setEnderecoLogradouro(String enderecoLogradouro) {
        this.enderecoLogradouro = enderecoLogradouro;
    }
    public String getEnderecoComplemento() {
        return this.enderecoComplemento;
    }
    
    public void setEnderecoComplemento(String enderecoComplemento) {
        this.enderecoComplemento = enderecoComplemento;
    }




}


