package com.netshoes.model.vo;
// Generated 22-Apr-2015 11:39:20 by Hibernate Tools 4.3.1

/**
 * Uf generated by hbm2java
 */
public class Uf  implements java.io.Serializable {

     private int ufCodigo;
     private String ufSigla;
     private String ufDescricao;

    public Uf() {
    }

	
    public Uf(int ufCodigo, String ufSigla, String ufDescricao) {
        this.ufCodigo = ufCodigo;
        this.ufSigla = ufSigla;
        this.ufDescricao = ufDescricao;
    }
   
    public int getUfCodigo() {
        return this.ufCodigo;
    }
    
    public void setUfCodigo(int ufCodigo) {
        this.ufCodigo = ufCodigo;
    }
    public String getUfSigla() {
        return this.ufSigla;
    }
    
    public void setUfSigla(String ufSigla) {
        this.ufSigla = ufSigla;
    }
    public String getUfDescricao() {
        return this.ufDescricao;
    }
    
    public void setUfDescricao(String ufDescricao) {
        this.ufDescricao = ufDescricao;
    }
}


